### ISSUE TITLE
Invalid command for adding a superuser on local system

### ISSUE THREAD

**Issue by smertins27** [prechelt/anwesende#1]
As mentioned in the README under point 4.7, the command does not work:
```./anw.sh production.sh onserver docker-compose run --rm django python manage.py createsuperuser --username superuser```

Follow command worked for me:
```./anw.sh production docker-compose run --rm django python manage.py createsuperuser --username superuser```

May you can update the README

**Comment by prechelt** [comment]
Thank you for the information! Done.

I found another such small mistake:  
` -   ./anw.sh production.sh onserver docker-compose logs`  
`+   ./anw.sh production onserver docker-compose logs`  
and one wrong additional line (to be removed) in the cronjob part:  
`-   set -a; source .envs/production.sh;`
