### ISSUE TITLE
Non-Docker setup

### ISSUE THREAD

**Issue by dequbed** [prechelt/anwesende#10]
I wanted to set up this software w/o Docker (and using our pre-existing postgres clustre) since I don't know how to use docker and less complexity means less potential for bugs or setup frustration.

This was mostly a non-issue but it required a modified `start`-file and a patch to `config/settings/production.py` which I'll attach for others wanting to do the same.

The general steps were as follows:
1. create a local user (`anwesende` with home directory `/var/lib/anwesende` in my case) and clone the repo
2. Run `anw.sh - prepare_env`.
3. Modify the env files as normal, but add `USE_DOCKER=no` to myenv.env
4. Run `anw.sh production install`. It will error due to missing docker_compose but it creates the `.envs/autogenerated.env` file which we'll need.
5. Install the python dependencies into a virtualenv, e.g. using pipenv: `$ pipenv install -r requirements.txt`
6. Apply the config patch: `$ git apply config.patch`
7. Start the server with `$ DJANGO_READ_DOT_ENV_FILE=True pipenv run ./start.sh` or with the service file attached below.

### start.sh:
```bash
#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# import the env
set -o allexport
source .envs/autogenerated.env
source .envs/production.sh
set +o allexport

python manage.py collectstatic --noinput
python manage.py migrate
python manage.py make_base_data

gunicorn config.wsgi \
    --worker-class gthread \
    --workers 5 \
    --threads 4 \
    --max-requests 4000 \
    --max-requests-jitter 111 \
    --bind localhost:5000
```

### config.patch
```patch
diff --git a/config/settings/production.py b/config/settings/production.py
index 736c42e..ef7bbcf 100644
--- a/config/settings/production.py
+++ b/config/settings/production.py
@@ -10,7 +10,7 @@ ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS")

 # DATABASES
 # ------------------------------------------------------------------------------
-DATABASES["default"] = env.db("DATABASE_URL")  # noqa F405
+#DATABASES["default"] = env.db("DATABASE_URL")  # noqa F405
 DATABASES["default"]["ATOMIC_REQUESTS"] = True  # noqa F405
 DATABASES["default"]["CONN_MAX_AGE"] = env.int("CONN_MAX_AGE", default=60)  # noqa F405

@@ -103,19 +103,19 @@ LOGGING = {
         "file": {
             "level": "DEBUG",
             "class": "logging.FileHandler",
-            "filename": '/djangolog/django.log',
+            "filename": '/var/lib/anwesende/anwesende/django.log',
             "formatter": "verbose",
         },
         "file_error": {
             "level": "ERROR",
             "class": "logging.FileHandler",
-            "filename": '/djangolog/django-errors.log',
+            "filename": '/var/lib/anwesende/anwesende/django-errors.log',
             "formatter": "verbose",
         },
         "file_search": {
             "level": "INFO",
             "class": "logging.FileHandler",
-            "filename": '/djangolog/django-requests.log',
+            "filename": '/var/lib/anwesende/anwesende/django-requests.log',
             "formatter": "verbose",
         },
     },
```

### anwesende.service 

```ini
[Unit]
Description=Run 'anwesende' service

[Service]
Type=simple
User=anwesende
Environment=DJANGO_READ_DOT_ENV_FILE=True
ExecStart=/usr/bin/pipenv run ./start.sh
WorkingDirectory=/var/lib/anwesende/anwesende

[Install]
WantedBy=multi-user.target
```

@prechelt if it isn't too much hassle maybe you could make the config.patch unnecessary in future releases? I don't really know Django enough to understand why *that* particular call to `env.db` errors with a key error, but it does. The application writes and reads to the (remote) postgres completely fine though.

**Comment by prechelt** [comment]
@dequbed It _is_ too much hassle, I'm afraid. I don't have the capacity to properly test this.

But the config is quite stable. If you put your patch in a fork, you should be able to integrate future changes without conflict.

Thanks for the contribution!
